
// this file is partially generated by tools
// do not change the layout

var THREE = require("three");

module.exports =
{
"general":
{
	url: "media/general_atlas.png",
	width: 36,
	height: 29,
	filter: THREE.LinearFilter,
	sprites:
	{
	"trap":[0,0,35,29],
	},
},
}
